### ISSUE TITLE
Question: Update  to Net6/NET7

### ISSUE THREAD

**Issue by GiuseppePatane** [queueit/KnownUser.V3.ASPNETCORE#4]
Hi, 
any plan to update this project? Net core 3.1 end of support is December 13, 2022. 

I tried to use it with net6 but had several memory problems. Fixed by making KnowUser a not static class.

Thanks.

**Comment by caddeo** [comment]
Hello,

Could you show me how you're using the KnownUser? I have been testing the .net 6 with our sample and haven't run into a any memory problems.
