### ISSUE TITLE
QueueIT.Security Types for .NET 6.0+

### ISSUE THREAD

**Issue by Avto9711** [queueit/KnownUser.V3.ASPNETCORE#5]
Im migrating an app which was written in .NET Framework. We are using a lot of types from the QueueIT.Security 2.0.5 package. 

Some of the types I'm currently using and I'd like to know how to replace them are: 
SessionValidationController
IValidateResult
EnqueueResult
AcceptedConfirmedResult
etc.. 

Is there any place or way or place where I can find the corresponding types for .NET 6.0+??

Thanks so much!

**Comment by caddeo** [comment]
Hi,

Sorry for not responding earlier - if you still have the issue, can you reach out to our technical engagement? They should be able to assist you.

**Comment by sarooghi** [comment]
The QueueIT.Security 2.0.5 is obsolete now ,  queue-it now offers connector for aspnet and aspnetcore with version 4 , please reach out to our support team , we are happy to help you to migrate to the latest version of our connector
